### ISSUE TITLE
Thank you buddy for creating this volume profile

### ISSUE THREAD

**Issue by ramakrishnamekala129** [Gregos5/Volume_profile_bybit#1]

**Comment by Gregos5** [comment]
Nw, I did it because I couldn't find one myself, But it not perfect. As you may have noticed the value areas are not on spot if you compare to other platforms (Exocharts, Atas, TradingV, ...) . This is because we can only get 1 min resolution and secondly, the volume per price is taken in the middle of each candle (avg(open, close). However,  the total volume of a 1 min candle should be equally distributed from Low to High of each candle. Hope that helps. Ill update the code when I have time
